import type { Exercise, Workout } from "@/types";
import { resolveExerciseImageUrl } from "@/lib/exercise-media";

const seedExercises: Exercise[] = [
  {
    id: "bench-press",
    name: "Bench Press",
    category: "Chest",
    targetSets: 4,
    targetReps: 8,
    isOptional: false,
    notes: "Latihan dorong utama untuk dada. Jaga bahu tetap stabil, turunkan palang dengan kontrol, lalu dorong kembali tanpa memantulkan palang di dada.",
    equipment: ["Barbel", "Bangku"],
    updatedAt: "2026-04-15T22:23:56.330863+02:00",
    imageUrl: "https://wger.de/media/exercise-images/192/Bench-press-1.png",
    videoUrl: "/media/exercise-videos/bench-press.mp4",
    instructions: [
      "Berbaring di bangku dengan posisi palang tepat di atas garis mata.",
      "Pijakkan kaki kuat di lantai dan pegang palang sedikit lebih lebar dari bahu.",
      "Turunkan palang perlahan ke area dada tengah dengan siku tetap terkontrol.",
      "Dorong palang ke atas sampai lengan hampir lurus tanpa mengangkat bahu dari bangku.",
    ],
  },
  {
    id: "incline-bench-press-dumbel",
    name: "Incline Bench Press - Dumbbell",
    category: "Chest",
    targetSets: 3,
    targetReps: 10,
    isOptional: false,
    notes: "Fokus pada dada bagian atas. Gunakan sudut bangku 30 sampai 45 derajat dan dorong dumbel secara stabil.",
    equipment: ["Dumbel", "Bangku miring"],
    updatedAt: "2026-04-15T22:23:56.012930+02:00",
    imageUrl: "https://wger.de/media/exercise-images/16/Incline-press-1.png",
    videoUrl: "/media/exercise-videos/incline-bench-press-dumbel.mp4",
    instructions: [
      "Atur bangku miring sekitar 30 sampai 45 derajat.",
      "Pegang dumbel di samping dada dengan pergelangan tetap netral.",
      "Dorong dumbel ke atas secara lurus dan terkontrol.",
      "Turunkan kembali perlahan sampai dada terasa meregang ringan.",
    ],
  },
  {
    id: "shoulder-press-dumbels",
    name: "Shoulder Press, Dumbbells",
    category: "Shoulders",
    targetSets: 3,
    targetReps: 10,
    isOptional: false,
    notes: "Latihan bahu utama. Jaga punggung tegak dan hindari mengayun badan saat mendorong beban.",
    equipment: ["Dumbel"],
    updatedAt: "2026-04-15T22:23:55.654931+02:00",
    imageUrl: "https://wger.de/media/exercise-images/123/dumbel-shoulder-press-large-1.png",
    videoUrl: "/media/exercise-videos/shoulder-press-dumbels.mp4",
    instructions: [
      "Duduk atau berdiri dengan punggung tegak dan otot inti aktif.",
      "Angkat dumbel setinggi bahu dengan telapak tangan menghadap depan.",
      "Dorong dumbel ke atas sampai lengan hampir lurus.",
      "Turunkan perlahan ke posisi awal tanpa kehilangan kontrol bahu.",
    ],
  },
  {
    id: "lateral-raises",
    name: "Lateral Raises",
    category: "Shoulders",
    targetSets: 3,
    targetReps: 12,
    isOptional: true,
    notes: "Gerakan isolasi untuk bahu samping. Gunakan beban ringan dan tempo stabil.",
    equipment: ["Dumbel"],
    updatedAt: "2026-04-15T22:23:55.570498+02:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/35/Dumbbell-lateral-raises-2.png",
    videoUrl: "/media/exercise-videos/lateral-raises.mp4",
    instructions: [
      "Berdiri tegak dengan dumbel di sisi tubuh.",
      "Tekuk siku sedikit dan jaga bahu tetap rileks.",
      "Angkat dumbel ke samping sampai sekitar setinggi bahu.",
      "Turunkan perlahan tanpa mengayun badan.",
    ],
  },
  {
    id: "dips",
    name: "Dips",
    category: "Chest",
    targetSets: 3,
    targetReps: 8,
    isOptional: true,
    notes: "Latihan berat badan untuk dada, bahu depan, dan trisep. Condongkan badan sedikit ke depan untuk menambah fokus dada.",
    equipment: ["Berat badan"],
    updatedAt: "2026-04-15T22:23:54.045674+02:00",
    imageUrl: "https://wger.de/media/exercise-images/194/34600351-8b0b-4cb0-8daa-583537be15b0.png",
    videoUrl: "/media/exercise-videos/dips.mp4",
    instructions: [
      "Pegang palang sejajar dan angkat tubuh sampai lengan menopang badan.",
      "Condongkan badan sedikit ke depan dan jaga bahu tetap stabil.",
      "Turunkan tubuh perlahan sampai siku menekuk nyaman.",
      "Dorong kembali ke atas tanpa mengunci siku terlalu keras.",
    ],
  },
  {
    id: "benchpress-dumbels",
    name: "Benchpress Dumbbells",
    category: "Chest",
    targetSets: 3,
    targetReps: 10,
    isOptional: true,
    notes: "Variasi tekan dada dengan dumbel untuk rentang gerak lebih bebas dan kontrol sisi kanan-kiri.",
    equipment: ["Bangku", "Dumbel"],
    updatedAt: "2026-04-15T22:23:56.016514+02:00",
    imageUrl: "https://wger.de/media/exercise-images/97/Dumbbell-bench-press-1.png",
    videoUrl: "/media/exercise-videos/benchpress-dumbels.mp4",
    instructions: [
      "Berbaring di bangku dengan dumbel di samping dada.",
      "Jaga kaki menapak dan bahu tetap menempel di bangku.",
      "Dorong dumbel ke atas sampai lengan hampir lurus.",
      "Turunkan perlahan sampai dada terasa meregang ringan.",
    ],
  },
  {
    id: "pull-ups",
    name: "Pull-up",
    category: "Back",
    targetSets: 4,
    targetReps: 8,
    isOptional: false,
    notes: "Latihan tarik berat badan untuk punggung. Prioritaskan rentang gerak dan kontrol tulang belikat.",
    equipment: ["Palang pull-up"],
    updatedAt: "2026-04-15T22:23:56.751242+02:00",
    imageUrl: "https://wger.de/media/exercise-images/475/b0554016-16fd-4dbe-be47-a2a17d16ae0e.jpg",
    videoUrl: "/media/exercise-videos/pull-ups.mp4",
    instructions: [
      "Pegang palang dengan pegangan sedikit lebih lebar dari bahu.",
      "Aktifkan punggung dengan menarik bahu turun terlebih dahulu.",
      "Tarik tubuh sampai dagu mendekati atau melewati palang.",
      "Turunkan tubuh perlahan sampai lengan kembali lurus terkontrol.",
    ],
  },
  {
    id: "pull-ups-on-machine",
    name: "Pull Ups on Machine",
    category: "Back",
    targetSets: 3,
    targetReps: 10,
    isOptional: true,
    notes: "Variasi pull-up dengan bantuan mesin agar repetisi lebih stabil.",
    equipment: ["Mesin pull-up bantuan"],
    updatedAt: "2026-04-15T22:23:55.167004+02:00",
    imageUrl: "https://wger.de/media/exercise-images/475/b0554016-16fd-4dbe-be47-a2a17d16ae0e.jpg",
    videoUrl: "/media/exercise-videos/pull-ups-on-machine.mp4",
    instructions: [
      "Atur beban bantuan sesuai kemampuan.",
      "Pegang pegangan dengan kuat dan posisikan lutut atau kaki pada bantalan.",
      "Tarik tubuh ke atas dengan fokus pada punggung.",
      "Turunkan perlahan tanpa melepas kontrol mesin.",
    ],
  },
  {
    id: "rowing-seated-narrow-pegangan",
    name: "Rowing seated, narrow grip",
    category: "Back",
    targetSets: 4,
    targetReps: 10,
    isOptional: false,
    notes: "Latihan tarik kabel untuk punggung tengah. Jaga dada terbuka dan jangan menarik dengan momentum badan.",
    equipment: ["Kabel tarik"],
    updatedAt: "2026-04-15T22:23:55.425143+02:00",
    imageUrl: "https://wger.de/media/exercise-images/512/b938437e-ff00-4679-9036-acb41bb28bbd.png",
    videoUrl: "/media/exercise-videos/rowing-seated-narrow-pegangan.mp4",
    instructions: [
      "Duduk tegak dengan kaki menapak pada pijakan.",
      "Pegang pegangan sempit dan jaga dada terbuka.",
      "Tarik pegangan ke arah perut atas sambil merapatkan tulang belikat.",
      "Kembalikan beban perlahan tanpa membungkukkan punggung.",
    ],
  },
  {
    id: "facepull",
    name: "Facepull",
    category: "Shoulders",
    targetSets: 3,
    targetReps: 15,
    isOptional: true,
    notes: "Gerakan untuk bahu belakang dan stabilitas tulang belikat. Cocok sebagai gerakan tambahan pada sesi tarik.",
    equipment: ["Kabel", "Tali kabel"],
    updatedAt: "2026-04-15T22:23:54.320038+02:00",
    imageUrl: "https://cdn.mos.cms.futurecdn.net/gWPK4bnmBf5M4vPQi6v6JR.jpg",
    videoUrl: "/media/exercise-videos/facepull.mp4",
    instructions: [
      "Pasang tali di kabel setinggi wajah atau dada atas.",
      "Pegang tali dan mundur sampai kabel tegang.",
      "Tarik tali ke arah wajah sambil membuka siku ke samping.",
      "Tahan sebentar, lalu kembali perlahan ke posisi awal.",
    ],
  },
  {
    id: "biceps-curls-with-barbell",
    name: "Biceps Curls With Barbell",
    category: "Arms",
    targetSets: 3,
    targetReps: 10,
    isOptional: false,
    notes: "Latihan utama untuk biceps. Jaga siku dekat tubuh dan hindari mengayun pinggang.",
    equipment: ["Barbel"],
    updatedAt: "2026-04-15T22:23:55.375060+02:00",
    imageUrl: "https://wger.de/media/exercise-images/74/Bicep-curls-1.png",
    videoUrl: "/media/exercise-videos/biceps-curls-with-barbell.mp4",
    instructions: [
      "Pegang barbel selebar bahu dengan telapak tangan menghadap atas.",
      "Jaga punggung tegak dan siku tetap dekat badan.",
      "Angkat barbel ke arah dada dengan kontrol biceps.",
      "Turunkan perlahan tanpa mengayun tubuh.",
    ],
  },
  {
    id: "hammer-curls",
    name: "Hammer Curls",
    category: "Arms",
    targetSets: 3,
    targetReps: 12,
    isOptional: true,
    notes: "Variasi curl dengan pegangan netral untuk biceps dan brachialis.",
    equipment: ["Dumbel"],
    updatedAt: "2026-04-15T22:23:54.216768+02:00",
    imageUrl: "https://wger.de/media/exercise-images/86/Bicep-hammer-curl-1.png",
    videoUrl: "/media/exercise-videos/hammer-curls.mp4",
    instructions: [
      "Pegang dumbel di sisi tubuh dengan telapak tangan saling menghadap.",
      "Jaga siku dekat badan dan bahu tidak ikut naik.",
      "Angkat dumbel ke arah bahu dengan pegangan tetap netral.",
      "Turunkan perlahan sampai lengan kembali lurus terkontrol.",
    ],
  },
  {
    id: "front-squats",
    name: "Front Squats",
    category: "Legs",
    targetSets: 4,
    targetReps: 8,
    isOptional: false,
    notes: "Variasi squat dengan posisi palang di depan untuk fokus kaki depan, otot inti, dan postur tegak.",
    equipment: ["Barbel"],
    updatedAt: "2026-04-15T22:23:55.585492+02:00",
    imageUrl: "https://wger.de/media/exercise-images/191/Front-squat-1-857x1024.png",
    videoUrl: "/media/exercise-videos/front-squats.mp4",
    instructions: [
      "Letakkan palang di depan bahu dengan siku terangkat.",
      "Buka kaki selebar bahu dan jaga otot inti aktif.",
      "Turun ke posisi squat dengan dada tetap tegak.",
      "Dorong lantai untuk kembali berdiri tanpa lutut masuk ke dalam.",
    ],
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    category: "Legs",
    targetSets: 3,
    targetReps: 10,
    isOptional: false,
    notes: "Latihan dorong pinggul untuk otot paha belakang dan otot bokong. Fokus pada dorongan pinggul ke belakang.",
    equipment: ["Barbel"],
    updatedAt: "2026-04-15T22:23:55.433530+02:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/58/Romanian-deadlift-2.png",
    videoUrl: "/media/exercise-videos/romanian-deadlift.mp4",
    instructions: [
      "Pegang barbel di depan paha dengan punggung netral.",
      "Dorong pinggul ke belakang sambil menurunkan palang mengikuti paha.",
      "Jaga lutut sedikit menekuk dan punggung tetap rata.",
      "Naik kembali dengan mengencangkan otot bokong dan otot paha belakang.",
    ],
  },
  {
    id: "leg-press",
    name: "Leg Press",
    category: "Legs",
    targetSets: 3,
    targetReps: 10,
    isOptional: false,
    notes: "Latihan mesin untuk kaki. Jaga punggung menempel dan kontrol kedalaman gerakan.",
    equipment: ["Mesin leg press"],
    updatedAt: "2026-04-15T22:23:55.074837+02:00",
    imageUrl: "https://wger.de/media/exercise-images/371/d2136f96-3a43-4d4c-9944-1919c4ca1ce1.webp",
    videoUrl: "/media/exercise-videos/leg-press.mp4",
    instructions: [
      "Duduk di mesin dengan punggung menempel penuh pada sandaran.",
      "Letakkan kaki di pijakan selebar bahu.",
      "Turunkan beban sampai lutut menekuk nyaman tanpa pinggul terangkat.",
      "Dorong pijakan kembali tanpa mengunci lutut terlalu keras.",
    ],
  },
  {
    id: "dumbel-lunges-walking",
    name: "Dumbbell Lunges Walking",
    category: "Legs",
    targetSets: 3,
    targetReps: 12,
    isOptional: true,
    notes: "Latihan unilateral untuk kaki dan stabilitas. Jaga langkah stabil dan lutut mengikuti arah kaki.",
    equipment: ["Dumbel"],
    updatedAt: "2026-04-15T22:23:56.366370+02:00",
    imageUrl: "https://wger.de/media/exercise-images/113/Walking-lunges-1.png",
    videoUrl: "/media/exercise-videos/dumbel-lunges-walking.mp4",
    instructions: [
      "Pegang dumbel di sisi tubuh dan berdiri tegak.",
      "Langkahkan satu kaki ke depan dengan jarak cukup panjang.",
      "Turunkan tubuh sampai lutut depan menekuk sekitar 90 derajat.",
      "Dorong kembali berdiri dan lanjutkan dengan kaki berikutnya.",
    ],
  },
  {
    id: "leg-curls-sitting",
    name: "Leg Curls (sitting)",
    category: "Legs",
    targetSets: 3,
    targetReps: 12,
    isOptional: false,
    notes: "Latihan isolasi otot paha belakang dengan mesin. Jaga pinggul tetap menempel di kursi.",
    equipment: ["Mesin leg curl"],
    updatedAt: "2026-04-15T22:23:53.335983+02:00",
    imageUrl: "https://wger.de/media/exercise-images/117/seated-leg-curl-large-1.png",
    videoUrl: "/media/exercise-videos/leg-curls-sitting.mp4",
    instructions: [
      "Atur bantalan mesin sesuai tinggi kaki.",
      "Duduk dengan pinggul dan punggung menempel stabil.",
      "Tekuk lutut untuk menarik bantalan ke bawah dengan otot paha belakang.",
      "Kembalikan perlahan tanpa membiarkan beban jatuh.",
    ],
  },
  {
    id: "standing-calf-raises",
    name: "Standing Calf Raises",
    category: "Calves",
    targetSets: 3,
    targetReps: 15,
    isOptional: true,
    notes: "Latihan betis berdiri. Gunakan rentang gerak penuh dan jeda singkat di puncak.",
    equipment: ["Mesin latihan betis"],
    updatedAt: "2026-04-15T22:23:56.267867+02:00",
    imageUrl: "https://wger.de/media/exercise-images/622/9a429bd0-afd3-4ad0-8043-e9beec901c81.jpeg",
    videoUrl: "/media/exercise-videos/standing-calf-raises.mp4",
    instructions: [
      "Berdiri di mesin latihan betis dengan posisi tubuh tegak.",
      "Turunkan tumit sampai betis terasa meregang.",
      "Dorong tubuh naik setinggi mungkin lewat ujung kaki.",
      "Tahan sebentar di puncak, lalu turunkan perlahan.",
    ],
  },
  {
    id: "hip-thrust",
    name: "Hip Thrust",
    category: "Legs",
    targetSets: 3,
    targetReps: 10,
    isOptional: true,
    notes: "Latihan otot bokong dengan fokus meluruskan pinggul. Gunakan bantalan palang agar lebih nyaman.",
    equipment: ["Barbel", "Bangku"],
    updatedAt: "2026-04-15T22:23:54.183961+02:00",
    imageUrl: "https://media.self.com/photos/626abcbdb2f1b9f02e220a68/4:3/w_2560,c_limit/Jowan-hip-thrust.jpg",
    videoUrl: "/media/exercise-videos/hip-thrust.mp4",
    instructions: [
      "Sandarkan punggung atas pada bangku dan letakkan palang di atas pinggul.",
      "Posisikan kaki di lantai dengan lutut menekuk nyaman.",
      "Dorong pinggul ke atas sampai badan membentuk garis dari bahu ke lutut.",
      "Turunkan pinggul perlahan sambil menjaga otot inti tetap aktif.",
    ],
  },
  {
    id: "machine-chest-press",
    name: "Machine Chest Press",
    category: "Chest",
    targetSets: 3,
    targetReps: 10,
    isOptional: true,
    notes: "Variasi dorong dada dengan mesin. Cocok untuk menambah volume tanpa terlalu banyak menuntut stabilisasi.",
    equipment: ["Mesin chest press"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Girl_doing_chest_press_machine_exercise.jpg",
    instructions: [
      "Atur tinggi kursi sampai pegangan sejajar dengan dada tengah.",
      "Duduk dengan punggung menempel dan kaki stabil di lantai.",
      "Dorong pegangan ke depan sampai lengan hampir lurus.",
      "Kembalikan pegangan perlahan sampai dada terasa meregang ringan.",
    ],
  },
  {
    id: "cable-fly",
    name: "Cable Fly",
    category: "Chest",
    targetSets: 3,
    targetReps: 12,
    isOptional: true,
    notes: "Gerakan isolasi dada menggunakan kabel. Fokus pada kontrol dan kontraksi dada, bukan beban terlalu berat.",
    equipment: ["Kabel", "Pegangan kabel"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Cable-crossover-2.png",
    instructions: [
      "Atur katrol di posisi sedang atau sedikit di atas bahu.",
      "Pegang kedua pegangan dan maju satu langkah sampai kabel tegang.",
      "Satukan tangan di depan dada dengan siku sedikit menekuk.",
      "Buka kembali perlahan sampai dada terasa meregang tanpa menarik bahu ke depan.",
    ],
  },
  {
    id: "incline-machine-chest-press",
    name: "Incline Machine Chest Press",
    category: "Chest",
    targetSets: 3,
    targetReps: 10,
    isOptional: true,
    notes: "Variasi mesin untuk dada atas. Gunakan tempo stabil dan jaga bahu tetap turun.",
    equipment: ["Mesin chest press miring"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Girl_doing_chest_press_machine_exercise.jpg",
    instructions: [
      "Atur kursi agar pegangan sejajar dengan dada atas.",
      "Tekan punggung ke sandaran dan aktifkan otot inti.",
      "Dorong pegangan ke atas depan sampai lengan hampir lurus.",
      "Turunkan perlahan dengan siku tetap terkontrol.",
    ],
  },
  {
    id: "pec-deck-fly",
    name: "Pec Deck Fly",
    category: "Chest",
    targetSets: 3,
    targetReps: 12,
    isOptional: true,
    notes: "Gerakan mesin untuk isolasi dada. Cocok sebagai finisher setelah gerakan dorong utama.",
    equipment: ["Mesin pec deck"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Pec_deck_Fly.jpg",
    instructions: [
      "Atur kursi sampai lengan sejajar dengan dada.",
      "Tempelkan punggung ke sandaran dan pegang bantalan atau pegangan.",
      "Satukan lengan di depan dada dengan gerakan halus.",
      "Kembalikan perlahan tanpa melepas ketegangan dada.",
    ],
  },
  {
    id: "push-up",
    name: "Push-up",
    category: "Chest",
    targetSets: 3,
    targetReps: 12,
    isOptional: true,
    notes: "Latihan berat badan untuk dada, bahu depan, dan trisep. Jaga tubuh tetap lurus selama gerakan.",
    equipment: ["Berat badan"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Push-up-1.png",
    instructions: [
      "Letakkan tangan sedikit lebih lebar dari bahu.",
      "Jaga tubuh membentuk garis lurus dari kepala sampai tumit.",
      "Turunkan dada ke arah lantai dengan siku terkontrol.",
      "Dorong tubuh kembali ke atas tanpa menurunkan pinggul.",
    ],
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    category: "Back",
    targetSets: 3,
    targetReps: 10,
    isOptional: true,
    notes: "Latihan tarik vertikal untuk punggung lebar. Fokus menarik siku ke bawah, bukan sekadar menarik tangan.",
    equipment: ["Mesin lat pulldown"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f8/PulldownMachineExercise.JPG",
    instructions: [
      "Duduk di mesin dan kunci paha di bawah bantalan.",
      "Pegang palang sedikit lebih lebar dari bahu.",
      "Tarik palang ke arah dada atas sambil menjaga dada terbuka.",
      "Kembalikan palang perlahan sampai lengan lurus terkontrol.",
    ],
  },
  {
    id: "one-arm-dumbbell-row",
    name: "One Arm Dumbbell Row",
    category: "Back",
    targetSets: 3,
    targetReps: 10,
    isOptional: true,
    notes: "Gerakan unilateral untuk punggung. Bantu menyeimbangkan kekuatan sisi kanan dan kiri.",
    equipment: ["Dumbel", "Bangku"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Cable-seated-rows-1.png",
    instructions: [
      "Letakkan satu tangan dan lutut di bangku dengan punggung netral.",
      "Pegang dumbel di tangan lainnya dengan lengan menggantung.",
      "Tarik dumbel ke arah pinggang sambil merapatkan tulang belikat.",
      "Turunkan perlahan tanpa memutar badan.",
    ],
  },
  {
    id: "straight-arm-pulldown",
    name: "Straight Arm Pulldown",
    category: "Back",
    targetSets: 3,
    targetReps: 12,
    isOptional: true,
    notes: "Gerakan isolasi untuk lat. Cocok sebagai aktivasi atau finisher sesi punggung.",
    equipment: ["Kabel", "Palang kabel"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/82/Wide-grip-lat-pull-down-1.gif",
    instructions: [
      "Atur katrol di posisi atas dan pegang palang dengan lengan hampir lurus.",
      "Mundur sedikit sampai kabel tegang.",
      "Tarik palang ke arah paha dengan bahu tetap turun.",
      "Kembalikan perlahan sampai lat terasa meregang.",
    ],
  },
  {
    id: "t-bar-row",
    name: "T-Bar Row",
    category: "Back",
    targetSets: 3,
    targetReps: 10,
    isOptional: true,
    notes: "Latihan row berat untuk punggung tengah. Jaga punggung netral dan dada terbuka.",
    equipment: ["T-bar row"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0e/T_bar_rows_2.svg",
    instructions: [
      "Posisikan kaki stabil dan pegang pegangan T-bar.",
      "Condongkan badan dengan punggung tetap netral.",
      "Tarik pegangan ke arah perut sambil merapatkan tulang belikat.",
      "Turunkan beban perlahan tanpa membulatkan punggung.",
    ],
  },
  {
    id: "arnold-press",
    name: "Arnold Press",
    category: "Shoulders",
    targetSets: 3,
    targetReps: 10,
    isOptional: true,
    notes: "Variasi shoulder press dengan rotasi. Gunakan beban moderat dan kontrol bahu sepanjang gerakan.",
    equipment: ["Dumbel"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/56/Arnold-press-2.png",
    instructions: [
      "Pegang dumbel di depan bahu dengan telapak tangan menghadap badan.",
      "Putar telapak tangan ke depan sambil mendorong dumbel ke atas.",
      "Turunkan kembali dengan rotasi yang sama ke posisi awal.",
      "Jaga punggung tegak dan jangan mengayun badan.",
    ],
  },
  {
    id: "rear-delt-fly",
    name: "Rear Delt Fly",
    category: "Shoulders",
    targetSets: 3,
    targetReps: 12,
    isOptional: true,
    notes: "Gerakan isolasi untuk bahu belakang. Prioritaskan kontrol, bukan beban besar.",
    equipment: ["Dumbel"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Lying-rear-lateral-raise-2.png",
    instructions: [
      "Condongkan badan ke depan dengan punggung netral.",
      "Pegang dumbel di bawah bahu dengan siku sedikit menekuk.",
      "Buka lengan ke samping sampai bahu belakang aktif.",
      "Turunkan perlahan tanpa mengayun badan.",
    ],
  },
  {
    id: "triceps-pushdown",
    name: "Triceps Pushdown",
    category: "Arms",
    targetSets: 3,
    targetReps: 12,
    isOptional: true,
    notes: "Gerakan isolasi trisep dengan kabel. Jaga siku dekat badan dan pergelangan tetap stabil.",
    equipment: ["Kabel", "Tali kabel"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/12/Triceps-pushdown-with-rope-1.gif",
    instructions: [
      "Atur katrol di posisi atas dan pegang tali atau palang.",
      "Dekatkan siku ke sisi tubuh dan jaga dada terbuka.",
      "Dorong pegangan ke bawah sampai lengan hampir lurus.",
      "Kembalikan perlahan tanpa siku bergerak maju.",
    ],
  },
  {
    id: "overhead-triceps-extension",
    name: "Overhead Triceps Extension",
    category: "Arms",
    targetSets: 3,
    targetReps: 12,
    isOptional: true,
    notes: "Variasi trisep untuk bagian kepala panjang. Gunakan rentang gerak nyaman untuk siku.",
    equipment: ["Dumbel"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Seated-overhead-triceps-extension-1.gif",
    instructions: [
      "Pegang dumbel dengan dua tangan di atas kepala.",
      "Tekuk siku untuk menurunkan dumbel di belakang kepala.",
      "Jaga siku mengarah ke depan dan tidak melebar berlebihan.",
      "Dorong dumbel kembali ke atas sampai lengan hampir lurus.",
    ],
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    category: "Legs",
    targetSets: 3,
    targetReps: 10,
    isOptional: true,
    notes: "Latihan unilateral untuk kaki depan dan otot bokong. Cocok untuk keseimbangan dan stabilitas.",
    equipment: ["Dumbel", "Bangku"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/82/Squats.svg",
    instructions: [
      "Letakkan satu kaki di belakang di atas bangku.",
      "Pegang dumbel di sisi tubuh atau gunakan berat badan dulu.",
      "Turunkan tubuh sampai lutut depan menekuk nyaman.",
      "Dorong lantai dengan kaki depan untuk kembali berdiri.",
    ],
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    category: "Legs",
    targetSets: 3,
    targetReps: 12,
    isOptional: true,
    notes: "Gerakan isolasi paha depan dengan mesin. Cocok sebagai tambahan setelah squat atau leg press.",
    equipment: ["Mesin leg extension"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/58/Leg-extensions-2-672x1024.png",
    instructions: [
      "Atur bantalan mesin di depan pergelangan kaki.",
      "Duduk dengan punggung menempel dan pegang pegangan mesin.",
      "Luruskan lutut sampai paha depan berkontraksi.",
      "Turunkan perlahan tanpa membiarkan beban jatuh.",
    ],
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    category: "Legs",
    targetSets: 3,
    targetReps: 12,
    isOptional: true,
    notes: "Variasi squat dengan dumbel di depan dada. Bagus untuk pola squat dan kontrol postur.",
    equipment: ["Dumbel"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/82/Squats.svg",
    instructions: [
      "Pegang dumbel vertikal di depan dada.",
      "Buka kaki selebar bahu dengan ujung kaki sedikit keluar.",
      "Turunkan pinggul sambil menjaga dada tetap tegak.",
      "Dorong lantai untuk kembali berdiri dengan lutut mengikuti arah kaki.",
    ],
  },
  {
    id: "plank",
    name: "Plank",
    category: "Core",
    targetSets: 3,
    targetReps: 30,
    isOptional: true,
    notes: "Latihan stabilitas otot inti. Hitungan repetisi dipakai sebagai durasi detik target.",
    equipment: ["Berat badan"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/35/Plank_exercise.svg",
    instructions: [
      "Letakkan siku di bawah bahu dan kaki lurus ke belakang.",
      "Jaga tubuh membentuk garis lurus dari kepala sampai tumit.",
      "Kencangkan perut dan bokong tanpa menahan napas.",
      "Pertahankan posisi selama target durasi.",
    ],
  },
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    category: "Core",
    targetSets: 3,
    targetReps: 12,
    isOptional: true,
    notes: "Gerakan otot perut dengan kabel. Fokus pada menekuk tulang rusuk ke arah panggul.",
    equipment: ["Kabel", "Tali kabel"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/74/Triceps-pushdown-1.gif",
    instructions: [
      "Pasang tali di katrol atas dan berlutut menghadap mesin.",
      "Pegang tali di dekat kepala dengan pinggul tetap stabil.",
      "Tekuk badan ke bawah menggunakan otot perut.",
      "Kembali perlahan tanpa menarik beban dengan tangan.",
    ],
  },
  {
    id: "dynamic-warm-up",
    name: "Dynamic Warm-up",
    category: "Warmup",
    targetSets: 1,
    targetReps: 60,
    isOptional: false,
    notes: "Pemanasan umum untuk menaikkan suhu tubuh sebelum masuk gerakan utama. Hitungan repetisi dipakai sebagai durasi detik target.",
    equipment: ["Berat badan"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Vitruvian_jumping_jacks.gif",
    instructions: [
      "Mulai dengan gerakan ringan seperti jumping jack atau jalan cepat di tempat.",
      "Gerakkan bahu, pinggul, dan pergelangan secara perlahan.",
      "Naikkan tempo bertahap sampai tubuh terasa hangat.",
      "Jangan langsung memakai intensitas tinggi di awal.",
    ],
  },
  {
    id: "shoulder-mobility",
    name: "Shoulder Mobility",
    category: "Warmup",
    targetSets: 1,
    targetReps: 12,
    isOptional: false,
    notes: "Pemanasan sendi bahu sebelum sesi push atau pull. Fokus pada rentang gerak dan kontrol.",
    equipment: ["Berat badan"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Ball-wall-circles-1.png",
    instructions: [
      "Berdiri tegak dan putar bahu ke depan dan belakang secara perlahan.",
      "Buka lengan ke samping lalu tarik tulang belikat ke belakang.",
      "Lakukan gerakan tanpa rasa nyeri dan tanpa mengayun cepat.",
      "Siapkan bahu agar stabil sebelum gerakan dorong atau tarik.",
    ],
  },
  {
    id: "hip-mobility",
    name: "Hip Mobility",
    category: "Warmup",
    targetSets: 1,
    targetReps: 12,
    isOptional: false,
    notes: "Pemanasan pinggul dan kaki sebelum sesi lower body. Cocok sebelum squat, deadlift, atau leg press.",
    equipment: ["Berat badan"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/82/Squats.svg",
    instructions: [
      "Berdiri stabil lalu lakukan squat ringan dengan rentang gerak nyaman.",
      "Gerakkan pinggul perlahan ke samping dan ke belakang.",
      "Jaga lutut mengikuti arah kaki.",
      "Gunakan tempo pelan sampai pinggul dan lutut terasa siap.",
    ],
  },
  {
    id: "full-body-stretch",
    name: "Full Body Stretch",
    category: "Cooldown",
    targetSets: 1,
    targetReps: 60,
    isOptional: false,
    notes: "Pendinginan ringan setelah sesi latihan. Hitungan repetisi dipakai sebagai durasi detik target.",
    equipment: ["Berat badan"],
    updatedAt: "2026-06-05T00:00:00.000+07:00",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Woman_on_the_yoga_mat_stretching_her_hamstrings_-_50398044188.jpg",
    instructions: [
      "Turunkan napas perlahan dan lakukan peregangan ringan.",
      "Tahan posisi nyaman pada area yang terasa tegang.",
      "Hindari memantul atau memaksa rentang gerak.",
      "Selesaikan dengan napas stabil sebelum menutup sesi.",
    ],
  },
];

export const defaultWorkouts: Workout[] = [
  {
    id: "push-foundation",
    name: "Push Dasar",
    dayOfWeek: "Monday",
    warmupIds: ["dynamic-warm-up", "shoulder-mobility"],
    exerciseIds: [
      "bench-press",
      "incline-bench-press-dumbel",
      "machine-chest-press",
      "shoulder-press-dumbels",
      "lateral-raises",
      "cable-fly",
      "pec-deck-fly",
      "dips",
      "benchpress-dumbels",
      "triceps-pushdown",
      "overhead-triceps-extension",
      "arnold-press",
      "push-up",
    ],
    cooldownIds: ["full-body-stretch"],
  },
  {
    id: "pull-foundation",
    name: "Pull Dasar",
    dayOfWeek: "Wednesday",
    warmupIds: ["dynamic-warm-up", "shoulder-mobility"],
    exerciseIds: [
      "pull-ups",
      "lat-pulldown",
      "rowing-seated-narrow-pegangan",
      "one-arm-dumbbell-row",
      "t-bar-row",
      "straight-arm-pulldown",
      "facepull",
      "rear-delt-fly",
      "biceps-curls-with-barbell",
      "hammer-curls",
      "pull-ups-on-machine",
    ],
    cooldownIds: ["full-body-stretch"],
  },
  {
    id: "legs-otot inti",
    name: "Kaki + Core",
    dayOfWeek: "Friday",
    warmupIds: ["dynamic-warm-up", "hip-mobility"],
    exerciseIds: [
      "front-squats",
      "goblet-squat",
      "romanian-deadlift",
      "leg-press",
      "leg-extension",
      "dumbel-lunges-walking",
      "bulgarian-split-squat",
      "hip-thrust",
      "leg-curls-sitting",
      "standing-calf-raises",
      "plank",
      "cable-crunch",
    ],
    cooldownIds: ["full-body-stretch"],
  },
  {
    id: "full-body",
    name: "Full Body",
    dayOfWeek: "Flexible",
    warmupIds: ["dynamic-warm-up", "shoulder-mobility", "hip-mobility"],
    exerciseIds: [
      "machine-chest-press",
      "lat-pulldown",
      "rowing-seated-narrow-pegangan",
      "front-squats",
      "romanian-deadlift",
      "shoulder-press-dumbels",
      "cable-fly",
      "leg-curls-sitting",
      "facepull",
      "triceps-pushdown",
      "hammer-curls",
      "hip-thrust",
      "plank",
    ],
    cooldownIds: ["full-body-stretch"],
  },
];

export const defaultExercises: Exercise[] = seedExercises.map((exercise) => ({
  ...exercise,
  imageUrl: resolveExerciseImageUrl(exercise.imageUrl),
}));
